
import __ASTRO_IMAGE_IMPORT_Z2aLSPj from "@assets/images/projects/196A1855.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fen%2Flightcraft.mdx";
import __ASTRO_IMAGE_IMPORT_12dKH1 from "@assets/images/projects/lightcraft.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fit%2Flightcraft.mdx";
import __ASTRO_IMAGE_IMPORT_eDgVe from "@assets/images/webptransform/taki-konsept/IMG_1298.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fen%2Fstudiovision.mdx";
import __ASTRO_IMAGE_IMPORT_Z2t2HDJ from "@assets/images/projects/artisanlens.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fit%2Fartisanlens.mdx";
import __ASTRO_IMAGE_IMPORT_1y8o4r from "@assets/images/projects/IMG_4890.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fen%2Fpixelcraft.mdx";
import __ASTRO_IMAGE_IMPORT_Z1DG7mv from "@assets/images/projects/pixelcraft.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fit%2Fpixelcraft.mdx";
import __ASTRO_IMAGE_IMPORT_1I99gO from "@assets/images/projects/IMG_1580.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fen%2Fartisanlens.mdx";
import __ASTRO_IMAGE_IMPORT_Z1fdWnw from "@assets/images/projects/studiovision.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fit%2Fstudiovision.mdx";
import __ASTRO_IMAGE_IMPORT_Z1cBVxn from "@assets/images/blog/remote-work-tech.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fthe-evolution-of-remote-work-technologies.mdx";
import __ASTRO_IMAGE_IMPORT_wVqE8 from "@assets/images/blog/ai-creativity.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fai-and-human-creativity.mdx";
import __ASTRO_IMAGE_IMPORT_ZBd4wV from "@assets/images/blog/digital-storytelling.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fthe-art-of-digital-storytelling.mdx";
import __ASTRO_IMAGE_IMPORT_Z20PN67 from "@assets/images/blog/sustainable-tech.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fthe-rise-of-sustainable-technology.mdx";
import __ASTRO_IMAGE_IMPORT_Z1oxGl2 from "@assets/images/blog/ai-creativity.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fit%2Fai-and-human-creativity.mdx";
import __ASTRO_IMAGE_IMPORT_1OtRek from "@assets/images/blog/sustainable-tech.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fit%2Fthe-rise-of-sustainable-technology.mdx";
import __ASTRO_IMAGE_IMPORT_ZeNlRM from "@assets/images/blog/digital-storytelling.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fit%2Fthe-art-of-digital-storytelling.mdx";
import __ASTRO_IMAGE_IMPORT_Z2ot04e from "@assets/images/blog/remote-work-tech.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fit%2Fthe-evolution-of-remote-work-technologies.mdx";
import __ASTRO_IMAGE_IMPORT_Z1r6dMC from "@assets/images/authors/mintaka.png?astroContentImageFlag=&importer=src%2Fcontent%2Fauthors%2Fit%2Fmarcus-chen.md";
import __ASTRO_IMAGE_IMPORT_Zwsaan from "@assets/images/authors/mintaka.png?astroContentImageFlag=&importer=src%2Fcontent%2Fauthors%2Fen%2Fmarcus-chen.md";
export default new Map([["@assets/images/projects/196A1855.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fen%2Flightcraft.mdx", __ASTRO_IMAGE_IMPORT_Z2aLSPj], ["@assets/images/projects/lightcraft.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fit%2Flightcraft.mdx", __ASTRO_IMAGE_IMPORT_12dKH1], ["@assets/images/webptransform/taki-konsept/IMG_1298.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fen%2Fstudiovision.mdx", __ASTRO_IMAGE_IMPORT_eDgVe], ["@assets/images/projects/artisanlens.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fit%2Fartisanlens.mdx", __ASTRO_IMAGE_IMPORT_Z2t2HDJ], ["@assets/images/projects/IMG_4890.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fen%2Fpixelcraft.mdx", __ASTRO_IMAGE_IMPORT_1y8o4r], ["@assets/images/projects/pixelcraft.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fit%2Fpixelcraft.mdx", __ASTRO_IMAGE_IMPORT_Z1DG7mv], ["@assets/images/projects/IMG_1580.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fen%2Fartisanlens.mdx", __ASTRO_IMAGE_IMPORT_1I99gO], ["@assets/images/projects/studiovision.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fit%2Fstudiovision.mdx", __ASTRO_IMAGE_IMPORT_Z1fdWnw], ["@assets/images/blog/remote-work-tech.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fthe-evolution-of-remote-work-technologies.mdx", __ASTRO_IMAGE_IMPORT_Z1cBVxn], ["@assets/images/blog/ai-creativity.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fai-and-human-creativity.mdx", __ASTRO_IMAGE_IMPORT_wVqE8], ["@assets/images/blog/digital-storytelling.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fthe-art-of-digital-storytelling.mdx", __ASTRO_IMAGE_IMPORT_ZBd4wV], ["@assets/images/blog/sustainable-tech.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fthe-rise-of-sustainable-technology.mdx", __ASTRO_IMAGE_IMPORT_Z20PN67], ["@assets/images/blog/ai-creativity.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fit%2Fai-and-human-creativity.mdx", __ASTRO_IMAGE_IMPORT_Z1oxGl2], ["@assets/images/blog/sustainable-tech.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fit%2Fthe-rise-of-sustainable-technology.mdx", __ASTRO_IMAGE_IMPORT_1OtRek], ["@assets/images/blog/digital-storytelling.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fit%2Fthe-art-of-digital-storytelling.mdx", __ASTRO_IMAGE_IMPORT_ZeNlRM], ["@assets/images/blog/remote-work-tech.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fit%2Fthe-evolution-of-remote-work-technologies.mdx", __ASTRO_IMAGE_IMPORT_Z2ot04e], ["@assets/images/authors/mintaka.png?astroContentImageFlag=&importer=src%2Fcontent%2Fauthors%2Fit%2Fmarcus-chen.md", __ASTRO_IMAGE_IMPORT_Z1r6dMC], ["@assets/images/authors/mintaka.png?astroContentImageFlag=&importer=src%2Fcontent%2Fauthors%2Fen%2Fmarcus-chen.md", __ASTRO_IMAGE_IMPORT_Zwsaan]]);
		